name: Read it later

on: push

jobs:
  read-it-later:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Directory Permissions
      run: sudo chmod -R 0777 storage/
      
    - name: Run Sail
      run: ./vendor/bin/sail up -d
      
    - name: Generate key
      run: ./vendor/bin/sail artisan key:generate
      
    - name: Laravel Migration command
      run: ./vendor/bin/sail artisan migrate
      
    - name: Database Seed Command
      run: ./vendor/bin/sail artisan db:seed
      
    - name: Swagger Generate
      run: ./vendor/bin/sail artisan l5-swagger:generate
      
    - name: Queue run command
      run: ./vendor/bin/sail artisan queue:work
