name: Mlbd Sample project

on: push

jobs:
  mlbd-sample-app:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Installation
        run: docker pull composer:latest

      - name: Composer installation
        run: docker run -it --rm -v $(pwd):/app composer install

      - name: Directory Permissions
        run: chmod -R 777 storage/

      - name: sail Start
        run: ./vendor/bin/sail up

      - name: Testing
        run: ./vendor/bin/sail artisan test
